const { contextBridge, ipcRenderer, webFrame } = require('electron');

contextBridge.exposeInMainWorld('api', {
  openJson: (title) => ipcRenderer.invoke('open-json', title),
  saveJson: (content, title) => ipcRenderer.invoke('save-json', content, title),
  minimize: () => ipcRenderer.send('win-minimize'),
  maximize: () => ipcRenderer.send('win-maximize'),
  close: () => ipcRenderer.send('win-close'),
  setZoom: (f) => webFrame.setZoomFactor(Math.min(1.4, Math.max(.8, Number(f) || 1))),
  setOnTop: (v) => ipcRenderer.send('win-ontop', !!v),
  loadSettings: () => ipcRenderer.sendSync('settings-get'),
  saveSettings: (obj) => ipcRenderer.send('settings-set', obj),
  loadNotes: () => ipcRenderer.sendSync('notes-get'),
  saveNotes: (obj) => ipcRenderer.send('notes-set', obj),
  openLink: (name) => ipcRenderer.send('open-link', name),
  openDataDir: () => ipcRenderer.send('open-data-dir'),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  getChangelog: () => ipcRenderer.invoke('get-changelog'),
  onUpdateProgress: (cb) => ipcRenderer.on('update-progress', (e, p) => cb(p)),
  getVersion: () => ipcRenderer.sendSync('app-version'),
  copyText: (txt) => ipcRenderer.invoke('copy-text', txt),
  eqSource: () => ipcRenderer.invoke('eq-source'),
  easterAudio: () => ipcRenderer.invoke('easter-audio'),
  exportSettings: (title) => ipcRenderer.invoke('export-settings', title),
  importSettings: (title) => ipcRenderer.invoke('import-settings', title),
  onCloseRequest: (cb) => ipcRenderer.on('close-request', () => { ipcRenderer.send('close-ack'); cb(); }),
  forceClose: () => ipcRenderer.send('win-force-close'),
});
